### PR TITLE
RED-1779: Fix clean dist folder

### PR DESCRIPTION
**Pull request by pawelkula**
Task: https://jira.bildtools.de/browse/RED-1779

**Proposed changes:**
- upgrade clean-webpack-plugin to version 2
- provide config path

**How to test:**
- add the branch to red-deliver: `yarn add spring-media/vussr#bugfix/RED-1779-clean-dist-folder`
- build red-delivery using production flag: `NODE_ENV=production yarn build`
- add any test file to the 'dist' folder
- run build with production flag again and check if your test file still exist

### CODE REVIEW

**Comment by pawelkula** [comment]
Waiting for merge https://github.com/spring-media/red-delivery/pull/779 to test the upgrade is enough to solve the issue

**Comment by mkai** [comment]
Version 4.0.0 is already published – you should bump the version to 4.0.1 for this PR.

**Comment by pawelkula** [comment]
> All old assets are still present on a rebuild.

The whole directory is removed, so how it is possible? Did you follow the steps mentioned in the description?

**Comment by veitbjarsch** [comment]
Ohh I see. Then another question. Why we are only clean up the dis folder in production mode? It should also be possible to run the cleanup task in dev mode.

**Comment by pawelkula** [comment]
> Ohh I see. Then another question. Why we are only clean up the dis folder in production mode? It should also be possible to run the cleanup task in dev mode.

Good question, maybe @mkai and @LukasBombach can tell us why we need a cleanup task only in the production mode. The more interesting question is: do we need a cleanup task at all (assuming that on the prod we create a brand new Docker image, on the dev we recreate files with every code change)?

**Comment by pawelkula** [comment]
> Ohh I see. Then another question. Why we are only clean up the dis folder in production mode? It should also be possible to run the cleanup task in dev mode.

Good question, maybe @mkai and @LukasBombach can tell us why we need a cleanup task only in the production mode. Maybe it is more efficient (for some reasons like caching, hot reloading) to not clean up the dist in the dev?

**Comment by LukasBombach** [comment]
* In the past, dev mode did not write anything to the disk at all. It was all in RAM using memory-fs, which is done by default by the webpack dev server
* we changed that behavior for some reason, there was a lib the could not handle memory-fs, but I can't rememeber what it was
* if we never went back to memory-fs I believe you guys can safely remove the dist folder in dev mode

**Pull request merged**
